### ISSUE TITLE
npm install 后,npm run dev出错

### ISSUE THREAD

**Issue by gzsvip** [liangxiaojuan/eleme#1]
D:\git\eleme\eleme-master\node_modules\semver\semver.js:293
    throw new TypeError('Invalid Version: ' + version);
    ^

TypeError: Invalid Version: D:\git\eleme\eleme-master>doskey ll=dir $*
3.10.10
    at new SemVer (D:\git\eleme\eleme-master\node_modules\semver\semver.js:293:11)
    at Range.test (D:\git\eleme\eleme-master\node_modules\semver\semver.js:1036:15)

**Comment by liangxiaojuan** [comment]
在没翻墙的 情况下 最好用 cnpm (用淘宝的镜像源)

**Comment by liangxiaojuan** [comment]
更新下 代码 ，如果没有一些环境，
请 下载 cnpm install -g vue-cli     cnpm install -g eslint     cnpm install -g eslint   ,在重启下终端，在执行npm run dev

**Comment by typ1758** [comment]
cnpm install -g vue-cli cnpm install -g eslint cnpm install -g eslint ,在重启下终端，在执行npm run dev
还是报错，起不起来

**Comment by ghost** [comment]
@typ1758 mac 是不是需要加 sudo? 
sudo npm install -g eslint

**Comment by ghost** [comment]
@typ1758 应该是npm版本的问题，你应该npm i npm 然后复制到node文件夹就ok了
