### ISSUE TITLE
header组件里面的弹框滚动穿透你是怎么处理的？

### ISSUE THREAD

**Issue by G-Veigar** [liangxiaojuan/eleme#10]
header组件点击商家，弹出商家弹框，我自己试着实现这个功能，但是发现弹框弹出后，滚动时背景跟着滚动，也就是滚动穿透，单我看你的代码，没有找到相关处理逻辑，你是怎么实现的？

**Comment by Ale-cc** [comment]
@G-Veigar 可以看看官方文档里的"事件修饰符"  ，看看如何处理事件冒泡的
http://cn.vuejs.org/v2/guide/events.html#事件修饰符

**Comment by G-Veigar** [comment]
@Ale-cc 可是在代码里面并没有找到啊？事件修饰符我知道的，但并没有在他的header找到他是怎么处理的

**Comment by glm196901** [comment]
z-index?
