### ISSUE TITLE
有个关于vue-router的问题想请教一下

### ISSUE THREAD

**Issue by siogo** [liangxiaojuan/eleme#11]
就是我在使用了vue-router之后，页面上挂载不出来我的app这个组件
这是我的app.vue页面
`<template>
  <div>
    <v-header></v-header>
    <div class="tab">
      <div class="tab-item">
        <router-link to="/goods" >商品</router-link>
      </div>
      <div class="tab-item">
        <router-link to="/ratings">评论</router-link>
      </div>
      <div class="tab-item">
        <router-link to="/seller">商家</router-link>
      </div>
    </div>
    <router-view></router-view>
  </div>
</template>`

这是main.js
`import Vue from 'vue';
import VueRouter from 'vue-router';
import App from './App';
import goods from './components/goods/goods';

Vue.use(VueRouter);

let routes = [
	{path:'/goods',component: goods}
]

let router = new VueRouter({
	routes
})

let app = new Vue({
	router
}).$mount('#app')

`

这是index.html
`<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>sell</title>
    <meta name="viewport" content="width=device-width,initial-scale=1.0,maximum-scale=1.0,minimum-scale=1.0,user-scalable=no">
    
  </head>
  <body>
    <div id="app"></div>
    
    <router-view></router-view>
  </body>
</html>`

麻烦告知一下要怎么弄才能挂载上去

**Comment by liangxiaojuan** [comment]
let routes = [
{path:'/',component: App}
{path:'/goods',component: goods},
] 你要把 app 这个组件用上才行啊

**Comment by siogo** [comment]
谢谢你

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by chendayang** [comment]
@siogo @liangxiaojuan 我碰到同样的问题了，我加载app组件了，但是页面是空白的，div#app内部是空的

main.js文件：
`import Vue from 'vue'
import VueRouter from 'vue-router'
import App from './App'
import goods from 'components/goods/goods.vue'
import seller from 'components/seller/seller.vue'
import ratings from 'components/ratings/ratings.vue'
Vue.config.productionTip = false

Vue.use(VueRouter)
let routes = [
  {path: '/', component: App},
  {path: '/goods', component: goods},
  {path: '/ratings', component: ratings},
  {path: '/seller', component: seller}
]
let router = new VueRouter({
  routes
})
let app = new Vue({
  router
})
app.$mount('#app')`

**Comment by Ale-cc** [comment]
@siogo @chendayang 少了export default app;没有导出组件，自然加载不到。
可以换一种更加简洁的写法
`
import Vue from 'vue'
import Router from 'vue-router'

Vue.use(Router)

import Hello from 'components/Hello'
import Types from 'components/Types'
import TabContainer from 'components/TabContainer'
import Picker from 'components/Picker'
import subTypes from 'components/subTypes'
import Search from 'components/Search'

export default new Router({
  mode: 'history',
  scrollBehavior: () => ({ y: 0 }),
  routes: [
    {path: '/', redirect: '/hello'},
    {path: '/hello',
      component: Hello,
      children: [
        {path: 'search', redirect: '/search'}
      ]
    },
    {path: '/search', name: 'Search', component: Search},
    {path: '/subtypes', name: 'subTypes', component: subTypes},
    {path: '/orders', name: 'TabContainer', component: TabContainer},
    {path: '/mine', name: 'Picker', component: Picker},
    {path: '*', redirect: '/'}
  ]
})
`
