### ISSUE TITLE
data.json你是怎么引入的，我在app.vue里写入和你用的一样的方法为什么报错

### ISSUE THREAD

**Issue by dongwenxu** [liangxiaojuan/eleme#12]
![image](https://cloud.githubusercontent.com/assets/22827993/23597985/4720f626-0272-11e7-891f-4444f97a32a7.png)

![image](https://cloud.githubusercontent.com/assets/22827993/23597993/4faedc2c-0272-11e7-93da-214eae017492.png)

**Comment by liangxiaojuan** [comment]
webpack 没配置好
