### ISSUE TITLE
大神你要是出一个入门+进阶的视频就人气暴涨了，国内网上找遍了，没有完整的，有的也是质量很差很差的。新手很需要，比如我这样的

### ISSUE THREAD

**Issue by Xmas118** [liangxiaojuan/eleme#18]

**Comment by orallin** [comment]
献上原版教程地址`http://coding.imooc.com/class/74.html`
顺便献上进阶教程`http://coding.imooc.com/learn/list/107.html`
出自同一位神之手的配方，同样的精彩，不同的味道，适合不同阶段的人哦

**Comment by xuezechao2012** [comment]
这个人真实不要脸了，代码都和别人一模一样，还有脸说是自己写的。关键还骗了1000多star！！！实在看不下去
