### ISSUE TITLE
install完run dev时报错，把src目录加入eslintignore才可以，是不是版本问题？

### ISSUE THREAD

**Issue by KaShing1** [liangxiaojuan/eleme#2]
E:\data2\eleme>cnpm install
| Installing es6-symbol@~3.1platform unsupported webpack@1.14.0 › watchpack@0.2.9 › chokidar@1.6.1 › fsevents@1.0.17 Pac
kage require os(darwin) not compatible with your platform(win32)
[fsevents@^1.0.0] optional install error: Package require os(darwin) not compatible with your platform(win32)
peerDependencies WARNING eslint-config-standard@6.2.1 requires a peer of eslint-plugin-promise@>=3.3.0 but eslint-plugin
-promise@2.0.1 was installed
√ All packages installed (608 packages installed from npm registry, use 32s, speed 128.62kB/s, json 765(3.96MB), tarbal
l 0B)
Recently updated (since 2016-12-29): 15 packages (detail see file node_modules/.recently_updates.txt)
  Today:
    → css-loader@0.25.0 › cssnano@3.10.0 › postcss-reduce-idents@2.4.0 (02:12:10)
    → webpack@1.14.0 › watchpack@0.2.9 › chokidar@1.6.1 › fsevents@1.0.17 (06:25:53)

E:\data2\eleme>cnpm run dev

> eleme@1.0.0 dev E:\data2\eleme
> node build/dev-server.js

Listening at http://localhost:8080

webpack: wait until bundle finished: /index.html
webpack built dbf20fe8c9302bfe7604 in 9428ms
Hash: dbf20fe8c9302bfe7604
Version: webpack 1.14.0
Time: 9428ms
 Asset     Size  Chunks       Chunk Names
app.js  2.29 MB       0       app

ERROR in ./src/App.vue

  ✘  http://eslint.org/docs/rules/space-before-function-paren  Missing space before function parentheses
  E:\data2\eleme\src\App.vue:39:9
    data() {
           ^

  ✘  http://eslint.org/docs/rules/space-before-function-paren  Missing space before function parentheses
  E:\data2\eleme\src\App.vue:49:12
    created() {
              ^

✘ 2 problems (2 errors, 0 warnings)

**Comment by liangxiaojuan** [comment]
要么把eslint关了  要么检查一下 node版本。和项目依赖报名的版本。

**Comment by liangxiaojuan** [comment]
更新下 代码 ，如果没有一些环境，
请 下载 cnpm install -g vue-cli     cnpm install -g eslint     cnpm install -g eslint   ,在重启下终端，在执行npm run dev

**Comment by KaShing1** [comment]
可以了~谢谢·
