### ISSUE TITLE
开源不代表你可以随便抄袭

### ISSUE THREAD

**Issue by Peanut429** [liangxiaojuan/eleme#25]
这个webapp项目是源码是基于GPL协议的，年轻人，注意点

**Comment by nathan-guo** [comment]
求原版地址

**Comment by Peanut429** [comment]
https://github.com/ustbhuangyi/vue-sell，开源项目分享是件好事，但请尊重作者版权

**Comment by mimistar** [comment]
好歹注明来源，结构都不该直接copy就放到这上面来

**Comment by Imchenlong** [comment]
https://github.com/ustbhuangyi/vue-sell
