### ISSUE TITLE
scroll

### ISSUE THREAD

**Issue by json-HB** [liangxiaojuan/eleme#4]
为什么不能向下拉，下面的内容看不到啊

**Comment by liangxiaojuan** [comment]
贴图片

**Comment by fuzhaohao** [comment]
@json-HB 你是不是用iphone6 plus的尺寸了？
用小屏一点的尺寸就可以滚动了
![gif](https://cloud.githubusercontent.com/assets/4248526/21963013/edae4a0c-db6c-11e6-8a2a-a0ac8fc18e5b.gif)

@liangxiaojuan 这是慕课网滴滴那个专家的项目吗？https://github.com/ustbhuangyi/vue-sell

**Comment by liangxiaojuan** [comment]
@fuzhaohao 对 素材 资料都是用的它的视频教程里面的资料。代码不完全和他一样。我是基于2.0都是自己写的
