### ISSUE TITLE
慕课网的？

### ISSUE THREAD

**Issue by junfengtang** [liangxiaojuan/eleme#5]
这是慕课网的实战课程吧？

**Comment by tempscript** [comment]
慕课网上的也来炫

**Comment by liangxiaojuan** [comment]
只是用了它的素材和图片文件。

**Comment by biaodigit** [comment]
一看就是慕课网的

**Comment by Code4Bull** [comment]
哈哈

**Comment by TerrenceFong** [comment]
项目结构也是跟慕课网的一样

**Comment by konglingwen94** [comment]
原版在这里[https://github.com/usbthuangyi/vue-sell.git](https://github.com/ustbhuangyi/vue-sell.git)

**Comment by konglingwen94** [comment]
原版在这里[https://github.com/usbthuangyi/vue-sell.git](https://github.com/usbthuangyi/vue-sell.git)

**Comment by ghost** [comment]
转发给的的含义是？


在2020年04月20日 10:11，孔令文 写道：

原版在这里https://github.com/usbthuangyi/vue-sell.git
